# controllers prefix, on prod it sets via WAR file name.
server:
  servlet:
    context-path: /api

spring:
  mail:
    default-encoding: UTF-8
    host: mail.${my.site.domain}
    port: 587
    username: no-reply@${my.site.domain}
    password: "YOUR_EMAIL_PASSWORD"
    properties.mail:
      user: no-reply@${my.site.domain}
      from: no-reply@${my.site.domain}
      smtp:
        #need this for EHLO check
        localhost: ${my.site.domain}
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  datasource:
    password: testtest
    platform: postgres
    url: jdbc:postgresql://localhost:5432/${my.db.name}
    username: postgres
  flyway:
    baseline-on-migrate: true
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
  http:
    log-request-details: true
  jackson:
    serialization:
      indent_output: true
  jmx:
    default-domain: ${my.db.name}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        connection:
          charSet: UTF-8
        temp:
          use_jdbc_metadata_defaults: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: PASTE_HERE_YOUR_OWN_GOOGLE_API_CLIENT_ID
            clientSecret: PASTE_HERE_YOUR_OWN_GOOGLE_API_CLIENT_SECRET
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: PASTE_HERE_YOUR_OWN_FACEBOOK_API_CLIENT_ID
            clientSecret: PASTE_HERE_YOUR_OWN_FACEBOOK_API_CLIENT_SECRET
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: PASTE_HERE_YOUR_OWN_GITHUB_API_CLIENT_ID
            clientSecret: PASTE_HERE_YOUR_OWN_GITHUB_API_CLIENT_SECRET
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          vk:
            clientName: VK
            clientId: PASTE_HERE_YOUR_OWN_VK_API_CLIENT_ID
            clientSecret: PASTE_HERE_YOUR_OWN_VK_API_CLIENT_SECRET
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            tokenName: code
            authenticationScheme: query
            clientAuthenticationScheme: form
            #use post, as vk needs clientId and clientSecret as request params and does not accepts Basic auth
            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            userNameAttribute: name
            scope:
              - email
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v4.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v4.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v4.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          vk:
            #revoke=1 needs to always show vk dialog
            authorizationUri: https://oauth.vk.com/authorize?revoke=1
            tokenUri: https://oauth.vk.com/access_token
            userInfoUri: https://api.vk.com/method/users.get?v=5.52&fields=photo_max
            userNameAttribute: response
            userInfoAuthenticationMethod: form

# logging properties
logging:
  file: logs/myLog.log
  level:
    org:
      flywaydb: INFO
      hibernate: ERROR
      hibernate.SQL: ERROR
      hibernate.type: ERROR
      springframework: INFO
      springframework.web: INFO
      springframework.web.filter.CommonsRequestLoggingFilter: TRACE
      root: ERROR
  pattern:
    console: '%d{HH:mm:ss.SSS} %msg%n'
# misc
auth:
  logout:
    socialLogout: false
my:
  #mail:
  mail:
    admin:
      address: admin@${my.site.domain}
  #db
  db:
    name: gp_db
  #site
  site:
    domain: you-domain.com
# front settings
angular:
  href: /en/
  port: :4200
